# Generated by Django 4.1.1 on 2022-10-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("artist", models.CharField(max_length=30)),
                ("album", models.CharField(max_length=20)),
                ("genre", models.CharField(max_length=20)),
                ("favorite", models.BooleanField()),
            ],
        ),
    ]
